### ISSUE TITLE
npmjs.com does not list newest version

### ISSUE THREAD

**Issue by Vinnl** [gampleman/quick_check.js#7]
I'm not sure how come, but at https://www.npmjs.com/package/quick_check it says "0.5.1 is the latest of 9 releases" on the right-hand side, whereas 0.6.0 is the actual latest version.

(Thanks for this project and the excellent documentation, by the way!)

**Comment by gampleman** [comment]
Good catch - but I'm not sure why. The [package.json](https://github.com/gampleman/quick_check.js/blob/master/package.json#L45) lists v0.6.0.

**Comment by gampleman** [comment]
Looks like the TravisCI deployment [failed](https://travis-ci.org/gampleman/quick_check.js/builds/73576998#L276), but didn't fail the build, which is why I didn't notice the issue. I'll try to republish v0.6 manually today or tomorrow. In the meantime, you can install straight from GitHub with `npm install gampleman/quick_check.js`.

**Comment by gampleman** [comment]
OK, I've published v0.6, and I've updated the .travis file, so hopefully this will not happen on the next version (I will monitor it manually). Thanks for the report!

**Comment by Vinnl** [comment]
Thanks!
